#!/bin/bash

OUTPUT=${1:-"/srv/olacvis/data"}
cd $(dirname $0)

./process-language-pages.py --languages languages.csv \
    --pages http://www.language-archives.org/language \
    --output $OUTPUT \
    --info \
    --refresh > update.log 2>&1

./create-summary.py --languages $OUTPUT --info >> update.log 2>&1